dist: trusty
sudo: false
language: ruby
cache: bundler

rvm: 2.2.0

jobs:
  include:
    - stage: test for pry
      rvm: 2.4.1
      before_install:
      - bash travis/.travis_pry.sh
      install: skip
      before_script: skip
      script: echo No pry found
    - stage: test
      env: DB=mysql
      gemfile: Gemfile
  exclude:  
    - env: DB=mysql
      gemfile: gemfiles/Gemfile.mysql57
    - env: DB=mysql57
      gemfile: gemfiles/Gemfile.mysql57
    - addons:
        mariadb: '10.0'
      env: DB=mariadb
      gemfile: Gemfile
    - addons:
        mariadb: '10.0'
      env: DB=mariadb
      gemfile: gemfiles/Gemfile.mysql57

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install ghostscript
  - sudo apt-get install graphviz
  - sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
  - qtchooser -qt=qt5
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake

  - bash travis/.travis_setup.sh

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake db:fixtures:load FIXTURES_PATH=spec/fixtures

script:
  - xvfb-run bundle exec rspec spec/features/

branches:
  only:
    - master
    - ui-design
    - fromthepage.com
    - indianapolis