name: benwbrum/fromthepage
author:
  name: Sara Brumfield
  email: saracarl@gmail.com
  url: 'http://sarabrumfield.blogspot.com'
copyright: 2015 Sara Brumfield
description: FromThePage is a wiki-like application for crowdsourcing transcription of handwritten documents.
